name: Docker
on:
  push:
    tags:
      - 'v*'
env:
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Run pnpm
      run: npm install -g pnpm && pnpm install && pnpm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to yiwen-ai registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.CR_REGISTRY }}
        username: ${{ secrets.CR_USERNAME }}
        password: ${{ secrets.CR_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.CR_REGISTRY }}/ywweb/webscraper
        tags: |
          type=semver,pattern={{raw}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
